
export type Emoji = string;
export type CodePoint = string;

export const shortNameEmoji: {[shortname:string]: Emoji} = {
    "angry":                        "😠",
    "anguished":                    "😧",
    "astonished":                   "😲",
    "blush":                        "😊",
    "clown":                        "🤡",
    "cold_sweat":                   "😰",
    "confounded":                   "😖",
    "confused":                     "😕",
    "cowboy":                       "🤠",
    "cry":                          "😢",
    "disappointed":                 "😞",
    "disappointed_relieved":        "😥",
    "dizzy_face":                   "😵",
    "drooling_face":                "🤤",
    "expressionless":               "😑",
    "fearful":                      "😨",
    "flushed":                      "😳",
    "frowning2":                    "☹️",
    "frowning":                     "😦",
    "grimacing":                    "😬",
    "grin":                         "😁",
    "grinning":                     "😀",
    "head_bandage":                 "🤕",
    "heart_eyes":                   "😍",
    "hugging":                      "🤗",
    "hushed":                       "😯",
    "innocent":                     "😇",
    "joy":                          "😂",
    "kissing":                      "😗",
    "kissing_closed_eyes":          "😚",
    "kissing_heart":                "😘",
    "kissing_smiling_eyes":         "😙",
    "laughing":                     "😆",
    "lying_face":                   "🤥",
    "mask":                         "😷",
    "money_mouth":                  "🤑",
    "nauseated_face":               "🤢",
    "nerd":                         "🤓",
    "neutral_face":                 "😐",
    "no_mouth":                     "😶",
    "open_mouth":                   "😮",
    "pensive":                      "😔",
    "persevere":                    "😣",
    "rage":                         "😡",
    "relieved":                     "😌",
    "rofl":                         "🤣",
    "rolling_eyes":                 "🙄",
    "scream":                       "😱",
    "sleeping":                     "😴",
    "sleepy":                       "😪",
    "slight_frown":                 "🙁",
    "slight_smile":                 "🙂",
    "smile":                        "😄",
    "smiley":                       "😃",
    "smirk":                        "😏",
    "sneezing_face":                "🤧",
    "sob":                          "😭",
    "stuck_out_tongue":             "😛",
    "stuck_out_tongue_closed_eyes": "😝",
    "stuck_out_tongue_winking_eye": "😜",
    "sunglasses":                   "😎",
    "sweat":                        "😓",
    "sweat_smile":                  "😅",
    "thermometer_face":             "🤒",
    "thinking":                     "🤔",
    "tired_face":                   "😫",
    "triumph":                      "😤",
    "unamused":                     "😒",
    "upside_down":                  "🙃",
    "weary":                        "😩",
    "wink":                         "😉",
    "worried":                      "😟",
    "yum":                          "😋",
    "zipper_mouth":                 "🤐",
};

export const emojiShortName: {[emoji:string]: string} = {
    "😠":   "angry",
    "😧":   "anguished",
    "😲":   "astonished",
    "😊":   "blush",
    "🤡":   "clown",
    "😰":   "cold_sweat",
    "😖":   "confounded",
    "😕":   "confused",
    "🤠":   "cowboy",
    "😢":   "cry",
    "😞":   "disappointed",
    "😥":   "disappointed_relieved",
    "😵":   "dizzy_face",
    "🤤":   "drooling_face",
    "😑":   "expressionless",
    "😨":   "fearful",
    "😳":   "flushed",
    "☹️":   "frowning2",
    "😦":   "frowning",
    "😬":   "grimacing",
    "😁":   "grin",
    "😀":   "grinning",
    "🤕":   "head_bandage",
    "😍":   "heart_eyes",
    "🤗":   "hugging",
    "😯":   "hushed",
    "😇":   "innocent",
    "😂":   "joy",
    "😗":   "kissing",
    "😚":   "kissing_closed_eyes",
    "😘":   "kissing_heart",
    "😙":   "kissing_smiling_eyes",
    "😆":   "laughing",
    "🤥":   "lying_face",
    "😷":   "mask",
    "🤑":   "money_mouth",
    "🤢":   "nauseated_face",
    "🤓":   "nerd",
    "😐":   "neutral_face",
    "😶":   "no_mouth",
    "😮":   "open_mouth",
    "😔":   "pensive",
    "😣":   "persevere",
    "😡":   "rage",
    "😌":   "relieved",
    "🤣":   "rofl",
    "🙄":   "rolling_eyes",
    "😱":   "scream",
    "😴":   "sleeping",
    "😪":   "sleepy",
    "🙁":   "slight_frown",
    "🙂":   "slight_smile",
    "😄":   "smile",
    "😃":   "smiley",
    "😏":   "smirk",
    "🤧":   "sneezing_face",
    "😭":   "sob",
    "😛":   "stuck_out_tongue",
    "😝":   "stuck_out_tongue_closed_eyes",
    "😜":   "stuck_out_tongue_winking_eye",
    "😎":   "sunglasses",
    "😓":   "sweat",
    "😅":   "sweat_smile",
    "🤒":   "thermometer_face",
    "🤔":   "thinking",
    "😫":   "tired_face",
    "😤":   "triumph",
    "😒":   "unamused",
    "🙃":   "upside_down",
    "😩":   "weary",
    "😉":   "wink",
    "😟":   "worried",
    "😋":   "yum",
    "🤐":   "zipper_mouth",
};

export const emojiCodePoint:{[emoji:string]:CodePoint } = {
    "😠": "1f620",
    "😧": "1f627",
    "😲": "1f632",
    "😊": "1f60a",
    "🤡": "1f921",
    "😰": "1f630",
    "😖": "1f616",
    "😕": "1f615",
    "🤠": "1f920",
    "😢": "1f622",
    "😞": "1f61e",
    "😥": "1f625",
    "😵": "1f635",
    "🤤": "1f924",
    "😑": "1f611",
    "😨": "1f628",
    "😳": "1f633",
    "☹️": "2639",
    "😦": "1f626",
    "😬": "1f62c",
    "😁": "1f601",
    "😀": "1f600",
    "🤕": "1f915",
    "😍": "1f60d",
    "🤗": "1f917",
    "😯": "1f62f",
    "😇": "1f607",
    "😂": "1f602",
    "😗": "1f617",
    "😚": "1f61a",
    "😘": "1f618",
    "😙": "1f619",
    "😆": "1f606",
    "🤥": "1f925",
    "😷": "1f637",
    "🤑": "1f911",
    "🤢": "1f922",
    "🤓": "1f913",
    "😐": "1f610",
    "😶": "1f636",
    "😮": "1f62e",
    "😔": "1f614",
    "😣": "1f623",
    "😡": "1f621",
    "😌": "1f60c",
    "🤣": "1f923",
    "🙄": "1f644",
    "😱": "1f631",
    "😴": "1f634",
    "😪": "1f62a",
    "🙁": "1f641",
    "🙂": "1f642",
    "😄": "1f604",
    "😃": "1f603",
    "😏": "1f60f",
    "🤧": "1f927",
    "😭": "1f62d",
    "😛": "1f61b",
    "😝": "1f61d",
    "😜": "1f61c",
    "😎": "1f60e",
    "😓": "1f613",
    "😅": "1f605",
    "🤒": "1f912",
    "🤔": "1f914",
    "😫": "1f62b",
    "😤": "1f624",
    "😒": "1f612",
    "🙃": "1f643",
    "😩": "1f629",
    "😉": "1f609",
    "😟": "1f61f",
    "😋": "1f60b",
    "🤐": "1f910",
}

export const codePointEmoji:{[codePoint:string]:Emoji } = {
    "1f620": "😠",
    "1f627": "😧",
    "1f632": "😲",
    "1f60a": "😊",
    "1f921": "🤡",
    "1f630": "😰",
    "1f616": "😖",
    "1f615": "😕",
    "1f920": "🤠",
    "1f622": "😢",
    "1f61e": "😞",
    "1f625": "😥",
    "1f635": "😵",
    "1f924": "🤤",
    "1f611": "😑",
    "1f628": "😨",
    "1f633": "😳",
    "2639" : "☹️",
    "1f626": "😦",
    "1f62c": "😬",
    "1f601": "😁",
    "1f600": "😀",
    "1f915": "🤕",
    "1f60d": "😍",
    "1f917": "🤗",
    "1f62f": "😯",
    "1f607": "😇",
    "1f602": "😂",
    "1f617": "😗",
    "1f61a": "😚",
    "1f618": "😘",
    "1f619": "😙",
    "1f606": "😆",
    "1f925": "🤥",
    "1f637": "😷",
    "1f911": "🤑",
    "1f922": "🤢",
    "1f913": "🤓",
    "1f610": "😐",
    "1f636": "😶",
    "1f62e": "😮",
    "1f614": "😔",
    "1f623": "😣",
    "1f621": "😡",
    "1f60c": "😌",
    "1f923": "🤣",
    "1f644": "🙄",
    "1f631": "😱",
    "1f634": "😴",
    "1f62a": "😪",
    "1f641": "🙁",
    "1f642": "🙂",
    "1f604": "😄",
    "1f603": "😃",
    "1f60f": "😏",
    "1f927": "🤧",
    "1f62d": "😭",
    "1f61b": "😛",
    "1f61d": "😝",
    "1f61c": "😜",
    "1f60e": "😎",
    "1f613": "😓",
    "1f605": "😅",
    "1f912": "🤒",
    "1f914": "🤔",
    "1f62b": "😫",
    "1f624": "😤",
    "1f612": "😒",
    "1f643": "🙃",
    "1f629": "😩",
    "1f609": "😉",
    "1f61f": "😟",
    "1f60b": "😋",
    "1f910": "🤐",
}

export function getEmojiSvgPath(emoji:Emoji):string {
    return `/static/${emojiCodePoint[emoji]}.svg`;
}

export function getCodePointSvgPath(codePoint:CodePoint):string {
    return `/static/${codePoint}.svg`;
}

export function getShortNameSvgPath(shortName:string):string {
    return `/static/${emojiCodePoint[shortNameEmoji[shortName]]}.svg`;
}

