
const emojiTable:{[shortname:string]: string} = {
    "angry":                       "😠", // unicode:"\\ud83d\\ude20"
    "anguished":                   "😧", // unicode:"\\ud83d\\ude27"
    "astonished":                  "😲", // unicode:"\\ud83d\\ude32"
    "blush":                       "😊", // unicode:"\\ud83d\\ude0a"
    "clown":                       "🤡", // unicode:"\\ud83e\\udd21"
    "cold_sweat":                  "😰", // unicode:"\\ud83d\\ude30"
    "confounded":                  "😖", // unicode:"\\ud83d\\ude16"
    "confused":                    "😕", // unicode:"\\ud83d\\ude15"
    "cowboy":                      "🤠", // unicode:"\\ud83e\\udd20"
    "cry":                         "😢", // unicode:"\\ud83d\\ude22"
    "disappointed":                "😞", // unicode:"\\ud83d\\ude1e"
    "disappointed_relieved":       "😥", // unicode:"\\ud83d\\ude25"
    "dizzy_face":                  "😵", // unicode:"\\ud83d\\ude35"
    "drooling_face":               "🤤", // unicode:"\\ud83e\\udd24"
    "expressionless":              "😑", // unicode:"\\ud83d\\ude11"
    "fearful":                     "😨", // unicode:"\\ud83d\\ude28"
    "flushed":                     "😳", // unicode:"\\ud83d\\ude33"
    "frowning2":                   "☹️", // unicode:"\\u2639\\ufe0f"
    "frowning":                    "😦", // unicode:"\\ud83d\\ude26"
    "grimacing":                   "😬", // unicode:"\\ud83d\\ude2c"
    "grin":                        "😁", // unicode:"\\ud83d\\ude01"
    "grinning":                    "😀", // unicode:"\\ud83d\\ude00"
    "head_bandage":                "🤕", // unicode:"\\ud83e\\udd15"
    "heart_eyes":                  "😍", // unicode:"\\ud83d\\ude0d"
    "hugging":                     "🤗", // unicode:"\\ud83e\\udd17"
    "hushed":                      "😯", // unicode:"\\ud83d\\ude2f"
    "innocent":                    "😇", // unicode:"\\ud83d\\ude07"
    "joy":                         "😂", // unicode:"\\ud83d\\ude02"
    "kissing":                     "😗", // unicode:"\\ud83d\\ude17"
    "kissing_closed_eyes":         "😚", // unicode:"\\ud83d\\ude1a"
    "kissing_heart":               "😘", // unicode:"\\ud83d\\ude18"
    "kissing_smiling_eyes":        "😙", // unicode:"\\ud83d\\ude19"
    "laughing":                    "😆", // unicode:"\\ud83d\\ude06"
    "lying_face":                  "🤥", // unicode:"\\ud83e\\udd25"
    "mask":                        "😷", // unicode:"\\ud83d\\ude37"
    "money_mouth":                 "🤑", // unicode:"\\ud83e\\udd11"
    "nauseated_face":              "🤢", // unicode:"\\ud83e\\udd22"
    "nerd":                        "🤓", // unicode:"\\ud83e\\udd13"
    "neutral_face":                "😐", // unicode:"\\ud83d\\ude10"
    "no_mouth":                    "😶", // unicode:"\\ud83d\\ude36"
    "open_mouth":                  "😮", // unicode:"\\ud83d\\ude2e"
    "pensive":                     "😔", // unicode:"\\ud83d\\ude14"
    "persevere":                   "😣", // unicode:"\\ud83d\\ude23"
    "rage":                        "😡", // unicode:"\\ud83d\\ude21"
    "relieved":                    "😌", // unicode:"\\ud83d\\ude0c"
    "rofl":                        "🤣", // unicode:"\\ud83e\\udd23"
    "rolling_eyes":                "🙄", // unicode:"\\ud83d\\ude44"
    "scream":                      "😱", // unicode:"\\ud83d\\ude31"
    "sleeping":                    "😴", // unicode:"\\ud83d\\ude34"
    "sleepy":                      "😪", // unicode:"\\ud83d\\ude2a"
    "slight_frown":                "🙁", // unicode:"\\ud83d\\ude41"
    "slight_smile":                "🙂", // unicode:"\\ud83d\\ude42"
    "smile":                       "😄", // unicode:"\\ud83d\\ude04"
    "smiley":                      "😃", // unicode:"\\ud83d\\ude03"
    "smirk":                       "😏", // unicode:"\\ud83d\\ude0f"
    "sneezing_face":               "🤧", // unicode:"\\ud83e\\udd27"
    "sob":                         "😭", // unicode:"\\ud83d\\ude2d"
    "stuck_out_tongue":            "😛", // unicode:"\\ud83d\\ude1b"
    "stuck_out_tongue_closed_eyes":"😝", // unicode:"\\ud83d\\ude1d"
    "stuck_out_tongue_winking_eye":"😜", // unicode:"\\ud83d\\ude1c"
    "sunglasses":                  "😎", // unicode:"\\ud83d\\ude0e"
    "sweat":                       "😓", // unicode:"\\ud83d\\ude13"
    "sweat_smile":                 "😅", // unicode:"\\ud83d\\ude05"
    "thermometer_face":            "🤒", // unicode:"\\ud83e\\udd12"
    "thinking":                    "🤔", // unicode:"\\ud83e\\udd14"
    "tired_face":                  "😫", // unicode:"\\ud83d\\ude2b"
    "triumph":                     "😤", // unicode:"\\ud83d\\ude24"
    "unamused":                    "😒", // unicode:"\\ud83d\\ude12"
    "upside_down":                 "🙃", // unicode:"\\ud83d\\ude43"
    "weary":                       "😩", // unicode:"\\ud83d\\ude29"
    "wink":                        "😉", // unicode:"\\ud83d\\ude09"
    "worried":                     "😟", // unicode:"\\ud83d\\ude1f"
    "yum":                         "😋", // unicode:"\\ud83d\\ude0b"
    "zipper_mouth":                "🤐", // unicode:"\\ud83e\\udd10"
};

export default emojiTable;