export interface IEmojiUnicode {
    emoji: string;
    unicode: string;
}

const emojiTable:{[shortname:string]: IEmojiUnicode} = {
    "angry":                       {emoji:"😠",       unicode:"\\ud83d\\ude20"},
    "anguished":                   {emoji:"😧",       unicode:"\\ud83d\\ude27"},
    "astonished":                  {emoji:"😲",       unicode:"\\ud83d\\ude32"},
    "blush":                       {emoji:"😊",       unicode:"\\ud83d\\ude0a"},
    "clown":                       {emoji:"🤡",       unicode:"\\ud83e\\udd21"},
    "cold_sweat":                  {emoji:"😰",       unicode:"\\ud83d\\ude30"},
    "confounded":                  {emoji:"😖",       unicode:"\\ud83d\\ude16"},
    "confused":                    {emoji:"😕",       unicode:"\\ud83d\\ude15"},
    "cowboy":                      {emoji:"🤠",       unicode:"\\ud83e\\udd20"},
    "cry":                         {emoji:"😢",       unicode:"\\ud83d\\ude22"},
    "disappointed":                {emoji:"😞",       unicode:"\\ud83d\\ude1e"},
    "disappointed_relieved":       {emoji:"😥",       unicode:"\\ud83d\\ude25"},
    "dizzy_face":                  {emoji:"😵",       unicode:"\\ud83d\\ude35"},
    "drooling_face":               {emoji:"🤤",       unicode:"\\ud83e\\udd24"},
    "expressionless":              {emoji:"😑",       unicode:"\\ud83d\\ude11"},
    "fearful":                     {emoji:"😨",       unicode:"\\ud83d\\ude28"},
    "flushed":                     {emoji:"😳",       unicode:"\\ud83d\\ude33"},
    "frowning2":                   {emoji:"☹️",       unicode:"\\u2639\\ufe0f"},
    "frowning":                    {emoji:"😦",       unicode:"\\ud83d\\ude26"},
    "grimacing":                   {emoji:"😬",       unicode:"\\ud83d\\ude2c"},
    "grin":                        {emoji:"😁",       unicode:"\\ud83d\\ude01"},
    "grinning":                    {emoji:"😀",       unicode:"\\ud83d\\ude00"},
    "head_bandage":                {emoji:"🤕",       unicode:"\\ud83e\\udd15"},
    "heart_eyes":                  {emoji:"😍",       unicode:"\\ud83d\\ude0d"},
    "hugging":                     {emoji:"🤗",       unicode:"\\ud83e\\udd17"},
    "hushed":                      {emoji:"😯",       unicode:"\\ud83d\\ude2f"},
    "innocent":                    {emoji:"😇",       unicode:"\\ud83d\\ude07"},
    "joy":                         {emoji:"😂",       unicode:"\\ud83d\\ude02"},
    "kissing":                     {emoji:"😗",       unicode:"\\ud83d\\ude17"},
    "kissing_closed_eyes":         {emoji:"😚",       unicode:"\\ud83d\\ude1a"},
    "kissing_heart":               {emoji:"😘",       unicode:"\\ud83d\\ude18"},
    "kissing_smiling_eyes":        {emoji:"😙",       unicode:"\\ud83d\\ude19"},
    "laughing":                    {emoji:"😆",       unicode:"\\ud83d\\ude06"},
    "lying_face":                  {emoji:"🤥",       unicode:"\\ud83e\\udd25"},
    "mask":                        {emoji:"😷",       unicode:"\\ud83d\\ude37"},
    "money_mouth":                 {emoji:"🤑",       unicode:"\\ud83e\\udd11"},
    "nauseated_face":              {emoji:"🤢",       unicode:"\\ud83e\\udd22"},
    "nerd":                        {emoji:"🤓",       unicode:"\\ud83e\\udd13"},
    "neutral_face":                {emoji:"😐",       unicode:"\\ud83d\\ude10"},
    "no_mouth":                    {emoji:"😶",       unicode:"\\ud83d\\ude36"},
    "open_mouth":                  {emoji:"😮",       unicode:"\\ud83d\\ude2e"},
    "pensive":                     {emoji:"😔",       unicode:"\\ud83d\\ude14"},
    "persevere":                   {emoji:"😣",       unicode:"\\ud83d\\ude23"},
    "rage":                        {emoji:"😡",       unicode:"\\ud83d\\ude21"},
    "relieved":                    {emoji:"😌",       unicode:"\\ud83d\\ude0c"},
    "rofl":                        {emoji:"🤣",       unicode:"\\ud83e\\udd23"},
    "rolling_eyes":                {emoji:"🙄",       unicode:"\\ud83d\\ude44"},
    "scream":                      {emoji:"😱",       unicode:"\\ud83d\\ude31"},
    "sleeping":                    {emoji:"😴",       unicode:"\\ud83d\\ude34"},
    "sleepy":                      {emoji:"😪",       unicode:"\\ud83d\\ude2a"},
    "slight_frown":                {emoji:"🙁",       unicode:"\\ud83d\\ude41"},
    "slight_smile":                {emoji:"🙂",       unicode:"\\ud83d\\ude42"},
    "smile":                       {emoji:"😄",       unicode:"\\ud83d\\ude04"},
    "smiley":                      {emoji:"😃",       unicode:"\\ud83d\\ude03"},
    "smirk":                       {emoji:"😏",       unicode:"\\ud83d\\ude0f"},
    "sneezing_face":               {emoji:"🤧",       unicode:"\\ud83e\\udd27"},
    "sob":                         {emoji:"😭",       unicode:"\\ud83d\\ude2d"},
    "stuck_out_tongue":            {emoji:"😛",       unicode:"\\ud83d\\ude1b"},
    "stuck_out_tongue_closed_eyes":{emoji:"😝",       unicode:"\\ud83d\\ude1d"},
    "stuck_out_tongue_winking_eye":{emoji:"😜",       unicode:"\\ud83d\\ude1c"},
    "sunglasses":                  {emoji:"😎",       unicode:"\\ud83d\\ude0e"},
    "sweat":                       {emoji:"😓",       unicode:"\\ud83d\\ude13"},
    "sweat_smile":                 {emoji:"😅",       unicode:"\\ud83d\\ude05"},
    "thermometer_face":            {emoji:"🤒",       unicode:"\\ud83e\\udd12"},
    "thinking":                    {emoji:"🤔",       unicode:"\\ud83e\\udd14"},
    "tired_face":                  {emoji:"😫",       unicode:"\\ud83d\\ude2b"},
    "triumph":                     {emoji:"😤",       unicode:"\\ud83d\\ude24"},
    "unamused":                    {emoji:"😒",       unicode:"\\ud83d\\ude12"},
    "upside_down":                 {emoji:"🙃",       unicode:"\\ud83d\\ude43"},
    "weary":                       {emoji:"😩",       unicode:"\\ud83d\\ude29"},
    "wink":                        {emoji:"😉",       unicode:"\\ud83d\\ude09"},
    "worried":                     {emoji:"😟",       unicode:"\\ud83d\\ude1f"},
    "yum":                         {emoji:"😋",       unicode:"\\ud83d\\ude0b"},
    "zipper_mouth":                {emoji:"🤐",       unicode:"\\ud83e\\udd10"},
};

export default emojiTable;